### PR TITLE
JS refactor

### PR DESCRIPTION
**Pull request by linusmarco**
This PR does a couple of things:
- Cleans up code formatting (indentation, spacing, other aesthetics)
- Updates all code to ES6 standards (const, let, arrow functions)
- Rearranges and modularizes some code
- Adds lots of inline documentation
    + Includes detailed explanation of how the animations work (ln. 144)

None of these changes should affect functionality

### CODE REVIEW

**Comment by timelyportfolio** [comment]
I agree these are very nice changes, but the RStudio Viewer does not support al ES6/ES2015.  Even though it complicates things, might want to a add a build step (babel) to the mix or add polyfills.

**Comment by linusmarco** [comment]
@timelyportfolio -- that's a good point. Here are my thoughts/reasoning.

It's impossible to polyfill all ES6 features, particularly keywords (let, const) and arrow functions, so the only option is to transpile. I had been thinking about adding in a build step but I still had not decided what the best way to do that would be. For a standard JS library I would just set up an NPM project and run it through that using Node. However, since the likely audience of this repo/library/widget is composed more of R users than JS users, I wouldn't want to require them to have node and run the build themselves. Which brings us to the solution of including both the ES6 source AND the transpiled "dist" code in the repo. I really hate to have build results in the repo on principle, and beyond that it will increase bundle size (albeit not by much), but it may be the only option. 

Have you integrated a build step cleanly into an R package like this before? Thoughts? I'm far from an expert on the R side of things, so maybe there's something I'm missing and we can use R's package install step to transpile or something...

**Comment by linusmarco** [comment]
Of course the other option is to write all the code to be compatible in the first place. But I'm not a big fan of that either. We're not living in 2010 anymore 😀

**Comment by timelyportfolio** [comment]
Unfortunately, there is not an easy answer, but hopefully I can give some options.  @bhaskarvk asked a while back if anybody had a good workflow for this, but I think the answer was silence.  In general, I think in an R package, we should always include build results in the R package repo since R users should not have to fool with the JS toolchain and the R package will require built JS anyways.  [Leaflet](https://github.com/rstudio/leaflet)  houses the source JavaScript in separate directory `javascript` and includes a `npm/grunt` [script](https://github.com/rstudio/leaflet/blob/master/Gruntfile.js) to build and move into `inst`.  I have done the same in [sunburstR](https://github.com/timelyportfolio/sunburstR).  Importantly, if we choose this route, we need to make sure that `.Rbuildignore` excludes the source JavaScript (see [line](https://github.com/timelyportfolio/sunburstR/blob/master/.Rbuildignore#L7)).

Another option if we want to stay in `R` and we are only transpiling would be to use `reactR::babel_transform`.  Even in this route, I would strongly suggest that the package author be responsible for the build and both source and built should be included in the repo.

Just my thoughts and happy to think through other paths.

**Comment by bhaskarvk** [comment]
RStudio uses very outdated versions of QT and webkit, and based on my last talk with @jcheng5 it's a non-trivial effort to port to the latest versions. I don't think widgets should support really old browsers, but having to support the older webkit in RStudio is still an issue.
It does look like most modern browsers (read IE11, Edge, FF, Chrome) have fairly complete ES6 support. See https://kangax.github.io/compat-table/es6/
Even if you go down the transpiling route, you will still have to check in the transpiled JS in to the GH repo, which is what we do in leaflet. One frustrating thing about transpiling is that variables are renamed and debugging the generated JS is that much harder.
Unfortunately I don't see solution in the near future for this.

**Comment by jcheng5** [comment]
I believe this is actively being worked on in RStudio now, but I would caution you just a bit--a lot of companies restrict their computers to run pinned versions of browsers and I don't know if those versions are all ES6 compatible. Also if people have smartphones that are stuck on old versions of Android or whatever. We use the transpiling approach for a lot of packages and it's not that bad once you get it set up--and if you want minimization, linting, and prettification, you'll need a build workflow anyway.

If it makes you feel better, there's no way you can get away from having at least some built artifacts checked into your repo anyway--not if you want to use roxygen :)

**Comment by linusmarco** [comment]
Thanks for your input, all! 

It sounds like the best route is going to be to set up a transpilation/build step and include both the src and dist versions in the package (but with src ignored in `.Rbuildignore`).

@ignacio82 -- I'll implement this and add it to this PR.

Added issue #16 to track this enhancement

**Pull request merged**
